### PR TITLE
Implements multiple HTTP header support

### LINKED ISSUE #225: Allow for multiple headers with same name in JsgiRequest
As per the spec, if there is more than one header with the same name, the value should be an array of strings rather than a string: http://wiki.commonjs.org/wiki/JSGI/Level0/A/Draft2#request.headers

Instead Ringo uses getHeader which only returns the first header: https://github.com/ringo/ringojs/blob/master/src/org/ringojs/jsgi/JsgiRequest.java#L78

The workaround should be to use getHeaders instead.

### PR DESCRIPTION
**Pull request by botic**
* `ringo/jsgi/response` switches to an array if multiple headers are present
* The JsgiServlet merges multiple headers into one single line according to the HTTP spec section 4.2

This fixes #225

### CODE REVIEW

**Comment by botic** [comment]
Since `Set-Cookie` is a **response** header, we can ignore it at the request level. Therefore the implemented logic in the `JsgiRequest` is working fine.

**Comment by oberhamsi** [comment]
I like that it fixes response.addHeaders() overwriting existing header values. 

Could the utils/http Headers class be useful here? What I like about that Headers class is that its values are still always strings (with "," multiple header values) and not mixed array/string values.

**Comment by botic** [comment]
`Set-Cookie` with its special status for responses is quite a jackass … I think `ringo/utils/http#Header` needs to follow the Node-style if it's responsible for request and response headers: https://nodejs.org/api/http.html#http_message_headers

**Comment by botic** [comment]
@oberhamsi ihmo `http.Headers` is only useful for request headers, not for response headers. This should be part of the documentation. Or is there any use case for the class together with HTTP responses? Then it needs more attention. Another option would be renaming it to `http.RequestHeaders` to explicitly tell the use case for it. Afais only the http client uses it.

**Pull request merged**
