### PR TITLE
eventsource on top of jetty9

### PR DESCRIPTION
**Pull request by oberhamsi**
this replaces my older EventSource branch. Benefitts over the old branch:

 * on top of jetty9; jetty9 ships with an EventSource servlet so no need to use my custom servlet
 * unit tests
 * example

ServerSentEvents complement Ringo's WebSocket support when uni-directional communication from server to client is enough. The tech is fairly old (it's just chunked responses with a standardized message format) and supported by all browser except IE. Good polyfills exist for IE.

Jetty9 EventSource servlet http://archive.eclipse.org/jetty/9.2.5.v20141112/apidocs/org/eclipse/jetty/servlets/EventSource.html

IE8+ polyfill https://github.com/Yaffle/EventSource/

### CODE REVIEW

**Comment by oberhamsi** [comment]
should the `onconnect` callback fire when the connection is open and the emitter is usable, or should it fire before that when jetty hands us a (passive) eventsource?

websocket calls `onconnect` only after the connection was established and is usable.

what's the use case for having an unopened eventsource?

**Comment by grob** [comment]
the only use-case i can think of would be if one could prevent the creation of an event source in the `onconnect` callback, eg. for authorization or authentication checks (a quick test revealed that returning null in the `newEventSource` method cancels the connection).

so we could either
- require that the onconnect callback must return the event source argument passed to it for an accepted connection, or
- require that it returns a boolean indicating that `newEventSource` should accept or deny the connection

the downside of this is that an EventSource instance would be created before the auth check, but that's just food for the garbage collector in case of a denied request. if we really don't want that we could split `onconnect` into two callbacks (`onconnect`/ `oninit`?), the first receiving just the request as argument for auth checks, the second the EventSource instance (in case the first callback returned true). but i don't think that's necessary.

in either case both eventsource and websocket should behave the same, and i'd love to get rid of the websocket `onCreate` callback i introduced in f14aeb6fd079fa18103607b83ca2e71e5f81a565.

**Comment by oberhamsi** [comment]
I now realize we don't have to do SSE at the jetty servlet level.

We could also do it as a stick middleware:
 * going through JSGIServlet would give us a JSGIRequest in `onconnect` (currently it's a ServletRequest) 
 * and we could put other stick middleware in front of it, like basicauth

here's a naive implementation of SEE for expressjs: https://github.com/zacbarton/node-server-sent-events/blob/master/index.js

**Comment by botic** [comment]
@oberhamsi Can we drop this PR and implement it in stick or is it still a goal for 0.12?

**Comment by oberhamsi** [comment]
yep, lets close it for now.

**Pull request closed without merging**
